AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake,bundle}'
    - !ruby/regexp /old_and_unused\.rb$/

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ClassLength:
  Max: 200

Layout/LineLength:
  Max: 120
  Ignore:
    - bin/bundle
