AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake,bundle}'
    - 'mongodb_data/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'lib/hgt_reader.rb'

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ClassLength:
  Max: 200
  Exclude:
    - 'spec/**/*'

Layout/LineLength:
  Max: 120
  Ignore:
    - bin/bundle

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Naming/VariableNumber:
  Exclude:
    - 'spec/**/*'
