services:
  mongodb:
    image: mongo:latest
    # environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: toor
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data:/data/db
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'mydb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./mysqldb_data:/data/db_mysql
      # - ./mysql_setup.sql:/docker-entrypoint-initdb.d/0_init.sql
  cosmosdb:
    restart: always
    container_name: "azure-cosmosdb-emulator"
    hostname: "azurecosmosemulator"
    image: 'mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest'
    mem_limit: 4GB
    tty: true
    ports:
      - '8081:8081' # Data Explorer
      - '8900:8900'
      - '8901:8901'
      - '8902:8902'
      - '10250:10250'
      - '10251:10251'
      - '10252:10252'
      - '10253:10253'
      - '10254:10254'
      - '10255:10255'
      - '10256:10256'
      - '10350:10350'
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=2
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=false
      # - AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=172.18.0.77
    # networks:
    #  default:
    #    ipv4_address: 172.18.0.77
  mystats:
    image: thewudu/mystats:latest
    ports: 
      - 80:3000
    environment:
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      PIDFILE: /tmp/pids/server.pid
    volumes:
      - ./import:/data/import
    tmpfs:
      - /tmp/pids/
