version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    # environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: toor
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data:/data/db
